// THIS FILE WAS AUTOGENERATED.
// DO NOT EDIT!

package ints

func Sort(data []int, lo, hi int) {
	if hi-lo <= 12 {
		// Do insertion sort.
		for i := lo + 1; i < hi; i++ {
			for j := i; j > lo && !(data[j-1] <= data[j]); j-- {
				data[j], data[j-1] = data[j-1], data[j]
			}
		}
		return
	}
	// Do quick sort.
	var (
		p = lo
		x = data[lo]
	)
	for i := lo + 1; i < hi; i++ {
		if data[i] <= x {
			p++
			data[p], data[i] = data[i], data[p]
		}
	}
	data[p], data[lo] = data[lo], data[p]

	if lo < p {
		Sort(data, lo, p)
	}
	if p+1 < hi {
		Sort(data, p+1, hi)
	}
}

func Search(data []int, key int) (int, bool) {
	// Binary search algorithm.
	var ok bool
	var i int
	{
		l := 0
		r := len(data)
		for !ok && l < r {
			m := l + (r-l)/2
			switch {
			case data[m] == key:
				ok = true
				r = m
			case data[m] < key:
				l = m + 1
			case data[m] > key:
				r = m
			}
		}
		i = r
		_ = i // in case when i not being used
	}
	return i, ok
}
